"""
Problem: Find the sum of the even valued terms in the Fibonacci sequence which starts with [1,2]. Sequence
         stops when the last term is 4 million or below.

Example: Fibonacci sequence for the sequence which starts with [2,7] is [2,7,9,16,25,41,...]

Fibonacci sequence: Sequence of numbers which is generated by adding the two previous terms.
                    Fib(n_start1, n_start2) = [n_start1, n_start2, (n_start1 + n_start2),
                    n_start2 + (n_start1 + n_start2), ...]

Even number: Number which is dividable by 2 and result in an exact number.
"""

import time

start_time = time.time()
limit = 4000000

fibonacci = [1, 2]
result = 0

for term in fibonacci:
    if (fibonacci[-1] + fibonacci[-2]) < limit:
        fibonacci.append(fibonacci[-1] + fibonacci[-2])
    if term % 2 == 0:
        result += term

print(result, time.time() - start_time)
